### ISSUE TITLE
Notification on new changes

### ISSUE THREAD

**Issue by chelmertz** [catharsis/gerrit-notify#2]
Besides changing the icon, perhaps you'd want an in-your-face notification. Would depend on some kind of polling that's not yet implemented.

**Comment by catharsis** [comment]
Yup, totally agree. We should poll in the background and update the icon somehow - possibly by compositing some bitmap on top of the icon we fetch from the server.

Another option would be adding a counter (indicating no. of incoming changes) to the icon or something.
