### ISSUE TITLE
Let menu items be settings

### ISSUE THREAD

**Issue by chelmertz** [catharsis/gerrit-notify#5]
I don't think anyone will come up with a covers-all mapping of link titles and URLs to map them to.

Someone might want to create "Incoming changes that I haven't +2:ed yet" and ... yeah, the possibilites are endless. It would be nice to have an ordered list of unlimited length of URL/description pairs.

If that's a good idea, we might want to have that ordered list exportable in order to have organisations prepare them for their non technical users, or packaging managers taking care of the setting up.

**Comment by catharsis** [comment]
I like this. I think the ones we have now are sane defaults, but I don't see any reason not to allow customizable queries. I'm not sure how we'd want those to work implementation-wise, however.
